version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pizza_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza_db
    volumes:
      - pizza_db_data:/var/lib/postgresql/data

volumes:
  pizza_db_data:
